# Generated by Django 5.1.6 on 2025-02-16 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_product_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='telegram_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
